"use client";
import { useState } from "react";
import { BookOpen, Check, FileText, GraduationCap, Languages, MessageCircle, Plus, Sparkles } from "lucide-react";
const refs=["Chapter 3 · Photosynthesis","Page 12 · Light reactions","Page 18 · ATP and NADPH"];
const cards=[["What is chlorophyll?","A green pigment that absorbs light energy for photosynthesis."],["Where do light reactions occur?","In the thylakoid membranes of chloroplasts."],["Main output?","ATP, NADPH, and oxygen."]];
export default function Home(){
 const [tab,setTab]=useState<"chat"|"quiz"|"cards">("chat"),[lang,setLang]=useState("English"),[q,setQ]=useState(""),[answer,setAnswer]=useState("The document is ready. Ask anything about your notes."),[card,setCard]=useState(0),[saved,setSaved]=useState(false);
 const ask=()=>{if(q.trim()){setAnswer(lang==="اردو"?"فوٹوسنتھیسز میں پودا روشنی کی توانائی کو کیمیائی توانائی میں بدلتا ہے۔":"Photosynthesis converts light energy into chemical energy. It takes place in the chloroplast and produces ATP, NADPH, and oxygen.");setQ("")}};
 return <main className="min-h-screen bg-[#071a1b] text-[#eaf4ee]"><header className="sticky top-0 z-10 border-b border-white/10 bg-[#071a1b]/90 backdrop-blur"><div className="mx-auto flex max-w-7xl items-center justify-between px-5 py-4 sm:px-8"><div className="flex items-center gap-3"><div className="grid h-10 w-10 place-items-center rounded-xl bg-[#d6f66a] text-[#082326]"><GraduationCap size={22}/></div><div><p className="text-lg font-bold">TaleemAI</p><p className="text-xs text-[#94aaa5]">Learn deeply. In your language.</p></div></div><button onClick={()=>setLang(lang==="English"?"اردو":"English")} className="flex items-center gap-2 rounded-full border border-white/15 px-4 py-2 text-sm"><Languages size={16}/>{lang}</button></div></header>
 <div className="mx-auto grid max-w-7xl gap-6 px-5 py-7 sm:px-8 lg:grid-cols-[235px_minmax(0,1fr)_270px]"><aside className="rounded-2xl border border-white/10 bg-[#0c2929] p-4"><button className="flex w-full items-center justify-center gap-2 rounded-xl bg-[#d6f66a] px-3 py-3 font-semibold text-[#092124]"><Plus size={17}/> New study space</button><p className="mt-7 px-2 text-xs font-semibold uppercase tracking-[.16em] text-[#8da29d]">Your library</p><button className="mt-3 flex w-full items-center gap-3 rounded-xl bg-white/10 px-3 py-3 text-left text-sm"><FileText size={17} className="text-[#d6f66a]"/><span><b className="block">Biology · Unit 3</b><small className="text-[#9db1ac]">1 document · Today</small></span></button><div className="mt-8 rounded-xl border border-[#d6f66a]/20 bg-[#d6f66a]/[.07] p-4"><Sparkles className="mb-2 text-[#d6f66a]" size={20}/><p className="text-sm font-semibold">Study smarter</p><p className="mt-1 text-xs leading-5 text-[#a8b9b5]">Upload notes, then turn them into explanations, quizzes and cards.</p></div></aside>
 <section><div className="mb-5 flex items-end justify-between"><div><p className="text-sm text-[#9db1ac]">Biology · Unit 3</p><h1 className="mt-1 text-3xl font-bold sm:text-4xl">Photosynthesis</h1></div><button onClick={()=>setSaved(!saved)} className="flex gap-2 rounded-xl border border-white/15 px-4 py-2.5 text-sm">{saved?<Check size={17}/>:<BookOpen size={17}/>}{saved?"Saved":"Save notes"}</button></div><div className="rounded-2xl border border-white/10 bg-[#f6f3e9] p-6 text-[#173234]"><span className="rounded-full bg-[#d6f66a] px-3 py-1 text-xs font-bold">AI SUMMARY</span><h2 className="mt-5 text-2xl font-bold">How plants turn light into fuel</h2><p className="mt-3 leading-7 text-[#45605e]">Photosynthesis is how plants use sunlight, water and carbon dioxide to make glucose. The light reactions capture energy; the Calvin cycle uses that energy to build sugar.</p><div className="mt-5 grid gap-3 sm:grid-cols-3">{["Sunlight","Water + CO₂","Glucose + O₂"].map((x,i)=><div key={x} className="rounded-xl border border-[#c9d7d0] bg-white px-4 py-3"><small> {i<2?"Input":"Output"}</small><p className="font-semibold">{x}</p></div>)}</div></div>
 <div className="mt-6 rounded-2xl border border-white/10 bg-[#0c2929]"><div className="flex border-b border-white/10">{([["chat","Ask AI",MessageCircle],["quiz","Quick quiz",Check],["cards","Flashcards",BookOpen]] as const).map(([id,label,Icon])=><button key={id} onClick={()=>setTab(id)} className={"flex items-center gap-2 px-4 py-4 text-sm font-semibold "+(tab===id?"border-b-2 border-[#d6f66a] text-[#d6f66a]":"text-[#98aba6]")}><Icon size={16}/>{label}</button>)}</div><div className="p-5">{tab==="chat"&&<><p className="leading-7">{answer}</p><div className="mt-4 flex flex-wrap gap-2">{refs.map(x=><span key={x} className="rounded-lg bg-white/8 px-3 py-1 text-xs text-[#a8bab5]">{x}</span>)}</div><div className="mt-6 flex gap-2"><input value={q} onChange={e=>setQ(e.target.value)} onKeyDown={e=>e.key==="Enter"&&ask()} className="min-w-0 flex-1 rounded-xl border border-white/15 bg-[#071a1b] px-4 py-3" placeholder="Ask about this chapter…"/><button onClick={ask} className="rounded-xl bg-[#d6f66a] px-5 font-bold text-[#082326]">Ask</button></div></>}{tab==="quiz"&&<><p className="text-sm text-[#a6b7b3]">Question 1 of 3</p><h3 className="mt-3 text-xl font-semibold">Which organelle is the main site of photosynthesis?</h3><div className="mt-5 grid gap-2 sm:grid-cols-2">{["Mitochondria","Chloroplast","Nucleus","Ribosome"].map(x=><button key={x} className="rounded-xl border border-white/10 px-4 py-3 text-left text-sm hover:border-[#d6f66a]">{x}</button>)}</div></>}{tab==="cards"&&<><p className="text-sm text-[#a6b7b3]">{card+1} / {cards.length}</p><article className="mt-4 rounded-xl bg-[#f6f3e9] p-8 text-center text-[#173234]"><p className="text-xs">FLASHCARD</p><h3 className="mt-3 text-2xl font-bold">{cards[card][0]}</h3><p className="mt-4">{cards[card][1]}</p></article><button onClick={()=>setCard((card+1)%cards.length)} className="mt-4 w-full rounded-xl bg-[#d6f66a] py-3 font-semibold text-[#082326]">Next card</button></>}</div></div></section>
 <aside className="rounded-2xl border border-white/10 bg-[#0c2929] p-5"><p className="text-xs font-semibold uppercase tracking-[.16em] text-[#8da29d]">Document</p><h2 className="mt-2 font-bold">Plant Energy Systems.pdf</h2><div className="mt-5 rounded-xl border border-dashed border-[#d6f66a]/40 p-4"><FileText size={22} className="text-[#d6f66a]"/><p className="mt-3 text-sm font-semibold">18 pages processed</p><p className="mt-1 text-xs text-[#9dafaa]">Every answer stays connected to your study material.</p></div><div className="mt-7 rounded-xl bg-white/5 p-4"><p className="text-2xl font-bold text-[#d6f66a]">42 min</p><p className="mt-1 text-sm text-[#a2b4b0]">Focused learning</p></div></aside></div></main>}
